PACKAGE_NAME="hid-asus-slashbar"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="hid-asus-slashbar"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hid/"

MAKE[0]="make KERNELDIR=${kernel_source_dir}"
CLEAN="make clean"

AUTOINSTALL="yes"
